# Generated by Django 4.1.3 on 2022-12-10 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name="userinfo", name="phonenum", field=models.BigIntegerField(),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="permission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app1.permission",
            ),
        ),
    ]
