# Generated by Django 4.1.3 on 2022-12-14 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_permission_alter_userinfo_phonenum_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=32, verbose_name="发信人")),
                ("recipient", models.CharField(max_length=32, verbose_name="收信人")),
                ("message", models.TextField(verbose_name="信息内容")),
                ("time", models.TimeField(verbose_name="发送时间")),
            ],
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="name",
            field=models.CharField(max_length=32, verbose_name="用户名"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="password",
            field=models.CharField(max_length=64, verbose_name="密码"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="permission",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.permission",
                verbose_name="权限",
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="phonenum",
            field=models.BigIntegerField(verbose_name="手机号"),
        ),
    ]
