# Generated by Django 4.1.3 on 2022-12-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_message_alter_userinfo_name_alter_userinfo_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="recipient_id",
            field=models.CharField(default=1, max_length=32, verbose_name="收信人id"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="sender_id",
            field=models.CharField(default=2, max_length=32, verbose_name="发信人id"),
            preserve_default=False,
        ),
    ]
