# Generated by Django 4.1.3 on 2022-12-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_message_recipient_id_message_sender_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="time",
            field=models.TimeField(auto_now=True, verbose_name="发送时间"),
        ),
    ]
