# Generated by Django 4.1.3 on 2022-12-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_alter_message_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="village",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("village", models.CharField(max_length=32)),
            ],
        ),
    ]
