# Generated by Django 4.1.3 on 2022-12-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0009_workorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="type",
            field=models.CharField(
                choices=[("0", "类型1"), ("1", "类型2"), ("2", "类型3"), ("3", "类型4")],
                default="0",
                max_length=10,
                verbose_name="工单类型",
            ),
        ),
    ]
