# Generated by Django 4.1.3 on 2023-01-04 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0011_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="handle_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="处理时间",
            ),
            preserve_default=False,
        ),
    ]
