# Generated by Django 4.1.3 on 2023-01-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0012_record_handle_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
        ),
    ]
