# Generated by Django 4.1.3 on 2023-01-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0013_alter_message_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="address_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                ("data", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
            ],
        ),
    ]
