# Generated by Django 4.1 on 2023-03-10 11:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_file_workorder_number_alter_file_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='处理记录'),
        ),
    ]
