# Generated by Django 4.1 on 2023-03-10 12:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_record_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='工单内容'),
        ),
    ]
