# Generated by Django 4.1 on 2023-03-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_workorder_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='creator',
            field=models.CharField(default=1, max_length=43, verbose_name='创建者'),
            preserve_default=False,
        ),
    ]
